export enum SexualIdentity {
  LESBIAN = 'Lesbian',
  GAY = 'Gay',
  BISEXUAL = 'Bisexual',
  PANSEXUAL = 'Pansexual',
  QUEER = 'Queer',
  ASEXUAL = 'Asexual',
  DEMISEXUAL = 'Demisexual',
  GRAYSEXUAL = 'Graysexual',
  POLYSEXUAL = 'Polysexual',
  OMNISEXUAL = 'Omnisexual',
  HETEROSEXUAL = 'Heterosexual',
  QUESTIONING = 'Questioning',
  ANDROSEXUAL = 'Androsexual',
  GYNOSEXUAL = 'Gynosexual',
  SKOLIOSEXUAL = 'Skoliosexual',
  SAPIOSEXUAL = 'Sapiosexual',
  LITHSEXUAL = 'Lithsexual',
  ABROSEXUAL = 'Abrosexual',
  AROFLUX = 'Aroflux',
  DEMIROMANTIC = 'Demiromantic',
  AROMANTIC = 'Aromantic',
  HOMOFLEXIBLE = 'Homoflexible',
  HOMOSEXUAL = 'Homosexual',
  HETEROFLEXIBLE = 'Heteroflexible',
}